### PR TITLE
Upgrade raven to latest stable version please

### PR DESCRIPTION
**Pull request by lancespeelmon**
```
npm i --save raven@2.1.0
```

### CODE REVIEW

**Comment by bendrucker** [comment]
What breaking changes were included in v2? Can you find a link?

**Comment by lancespeelmon** [comment]
Well all the tests pass, so no breaking changes? 😄 Let me see if I can find a link...

**Comment by lancespeelmon** [comment]
From what I can tell, the major semantic version did not include any breaking changes... 
https://github.com/getsentry/raven-node/blob/master/History.md

**Comment by lancespeelmon** [comment]
I see, the change is more of a runtime behavior change, not API change:
* Be aware when upgrading: it is possible that with raven-node 2.0, your node process will shut down from exceptions where it previously did not

**Comment by bendrucker** [comment]
Yeah to me that's enough reason for a breaking release here

**Comment by lancespeelmon** [comment]
awesome thanks!

**Pull request merged**
